from __future__ import annotations

from enum import StrEnum


class UserRole(StrEnum):
    SUPER_ADMIN = "SUPER_ADMIN"
    ORG_ADMIN = "ORG_ADMIN"
    SITE_MANAGER = "SITE_MANAGER"
    SECURITY_GUARD = "SECURITY_GUARD"
    VIEWER = "VIEWER"


class GateMode(StrEnum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    MIXED = "MIXED"


class Direction(StrEnum):
    ENTRY = "ENTRY"
    EXIT = "EXIT"
    BOTH = "BOTH"


class CameraStatus(StrEnum):
    ONLINE = "ONLINE"
    OFFLINE = "OFFLINE"
    UNKNOWN = "UNKNOWN"
    ERROR = "ERROR"
    CONNECTING = "CONNECTING"


class StreamType(StrEnum):
    RTSP = "RTSP"
    ONVIF = "ONVIF"


class VisitStatus(StrEnum):
    CURRENTLY_INSIDE = "CURRENTLY_INSIDE"
    COMPLETED = "COMPLETED"
    EXIT_WITHOUT_MATCH = "EXIT_WITHOUT_MATCH"
    MANUALLY_RESOLVED = "MANUALLY_RESOLVED"


class SyncStatus(StrEnum):
    PENDING = "PENDING"
    SYNCED = "SYNCED"
    FAILED = "FAILED"


class SourceType(StrEnum):
    EDGE = "EDGE"
    MOCK = "MOCK"
    MANUAL = "MANUAL"


class SnapshotKind(StrEnum):
    FRAME = "FRAME"
    VEHICLE_CROP = "VEHICLE_CROP"
    PLATE_CROP = "PLATE_CROP"


class EdgeAgentStatus(StrEnum):
    CONNECTED = "CONNECTED"
    DISCONNECTED = "DISCONNECTED"
    UNKNOWN = "UNKNOWN"


class AuditAction(StrEnum):
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    ORGANIZATION_CREATE = "ORGANIZATION_CREATE"
    ORGANIZATION_UPDATE = "ORGANIZATION_UPDATE"
    SITE_CREATE = "SITE_CREATE"
    SITE_UPDATE = "SITE_UPDATE"
    GATE_CREATE = "GATE_CREATE"
    GATE_UPDATE = "GATE_UPDATE"
    GATE_DELETE = "GATE_DELETE"
    CAMERA_CREATE = "CAMERA_CREATE"
    CAMERA_UPDATE = "CAMERA_UPDATE"
    CAMERA_DELETE = "CAMERA_DELETE"
    CAMERA_ENABLE = "CAMERA_ENABLE"
    CAMERA_DISABLE = "CAMERA_DISABLE"
    CAMERA_TEST = "CAMERA_TEST"
    USER_CREATE = "USER_CREATE"
    USER_UPDATE = "USER_UPDATE"
    EVENT_CORRECT = "EVENT_CORRECT"
    EVENT_CLASSIFY = "EVENT_CLASSIFY"
    EVENT_DELETE = "EVENT_DELETE"
    VISIT_RESOLVE = "VISIT_RESOLVE"
    REPORT_EXPORT = "REPORT_EXPORT"
    MOCK_EVENT = "MOCK_EVENT"
